### ISSUE TITLE
Ruckus ZD 1200 Support

### ISSUE THREAD

**Issue by apvlv** [welkson/ruckus-guest-py#3]
Hello,

thank you for the script. Unfortunately it will not work with Ruckus ZD 1200. Which Controller you have used with this script? The generate guest pass interface is looking very similar on my 1200, though i get control not found errors.

`Traceback (most recent call last):
  File "ruckus.py", line 47, in <module>
    br.form['fullname'] = user
  File "/Library/Python/2.7/site-packages/mechanize/_form.py", line 2780, in __setitem__
    control = self.find_control(name)
  File "/Library/Python/2.7/site-packages/mechanize/_form.py", line 3101, in find_control
    return self._find_control(name, type, kind, id, label, predicate, nr)
  File "/Library/Python/2.7/site-packages/mechanize/_form.py", line 3185, in _find_control
    raise ControlNotFoundError("no control matching "+description)
mechanize._form.ControlNotFoundError: no control matching name 'fullname'`

i see that the controls with this name exist in the html of the page, but i see also that they are outside of the first form which is probably the cause of the error. Do you have a workaround about this?

```
<table id="userpass" class="separatorTbl">
<form id="form-guest" method="post" action="guestinfo.jsp">
</form><tr class="gap"><th>&nbsp;</th><td>&nbsp;</td></tr>
<tr><th class="nowrap">Creation Type</th><td>
<input type="radio" name="gentype" id="single" value="single" onclick="reflectGenType();" checked="checked" /><label for="single">Single</label>
<input type="radio" name="gentype" id="multiple" value="multiple" onclick="reflectGenType();" /><label for="multiple">Multiple</label>
</td></tr>
<tr id="row-fullname"><th>Full Name <span class="required">*</span></th><td><input type="text" maxlength="64" id="fullname" name="fullname" value="" /></td></tr>
<tr><th>Valid for <span class="required">*</span></th>
<td><input type="text" size="5" maxlength="5" id="duration" name="duration" value="1" />
<select name="duration-unit" id="duration-unit">
<option value="day_Days">Days</option>
<option value="hour_Hours">Hours</option>
<option value="week_Weeks">Weeks</option>
</select>
</td>
</tr>
<tr><th>WLAN <span class="required">*</span></th>
<td>
<select name="guest-wlan" id="guest-wlan">
</select>
</td>
</tr>
<tr id="row-Email"><th>Email</th>
<td><input type="text" maxlength="64" id="email" name="email" value="" /></td></tr>
<tr id="row-PhoneNumber"><th>Phone Number</th>
<td>
<!-- &lt;input type="text" id="countrycode" name="countrycode" size="5" maxlength="5" value="" /&gt; -->
<input type="text" maxlength="30" size="12" id="phonenumber" name="phonenumber" value="4081234567" />
</td>
</tr>
<tr id="row-key"><th valign="top">Key <span class="required">*</span></th>
<td><input type="text" id="key" name="key" maxlength="16" value="DMGLJ-PHTZB" /></td></tr>
<tr id="row-remarks"><th valign="top">Remarks<p class="small">(Max length is 64)</p></th>
<td><textarea id="remarks" name="remarks" cols="30" rows="3" value=""></textarea></td></tr>
<tr id="row-number"><th>Number</th><td>
<input id="number" name="number" type="text" size="5" value="5" />
<span> or specified by profile below</span>
<input id="createToNum" name="createToNum" type="hidden" value="" />
<input id="batchpass" name="batchpass" type="hidden" value="" />
</td></tr>
````

Thank you!

**Comment by welkson** [comment]
Hello @pvlvsk 

I tested on Ruckus Zone Director model ZD5100-00 (version 9.13.3.0 build 133).

Screenshot:
![Screenshot1](https://user-images.githubusercontent.com/757447/58818209-ed8d6000-8603-11e9-843c-d38298b5ba8c.png)
